name: hippo_analytic
description: "A Flutter package for deep linking and analytics tracking with install referrer support."
version: 1.0.0+1
homepage: https://github.com/imskshivam/deeplink_analytic.git

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.0
  http: ^1.6.0
  device_info_plus: ^11.3.3
  package_info_plus: ^8.1.0
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Plugin configuration
plugin:
  platforms:
    android:
      package: com.hippo_analytic.app
      pluginClass: DeepLinkPackagePlugin